=== UKrawczyk-R/kurs_1_html_css_js/cwieczenie-xml+dtd/wizytowki.dtd
<!ELEMENT wizytowki (wizytowka)>

<!ATTLIST wizytowka id ID #REQUIED>
<!ELEMENT wizytowka (imie, nazwisko, (tel | e-mail)+, website)> <!--nawias grupuje sprawia ze elementy sa jednoscia-->

<!ELEMENT imie (#PCDATA)>

<!ELEMENT nazwisko (#PCDATA)>

<!ELEMENT tel (#PCDATA)>
<!ATTRLIST tel typ (komorka | stacjonarny) #REQUIED
			inny_atrybut CDATA #IMPLIED>
<!--<!ATTLIST telefon typ (komorka | stacjonarny) #REQUIED>-->

<!ELEMENT e-mail (#PCDATA)>

<!ELEMENT website (#PCDATA)>



<!--
	1.komentarze dtd jak w html
	2.aby zadeklarować jakis element piszemy<!ELEMENT nastepnie nzawę elementu i zawartość elementu>
	3.rodzaje zawartości elementów: EMPTY{np <br />}, ANY, 
	4. wizytowki (wizytowka)- tag wizytowki posiada dokładnie 1 element o nazwie wizytowka
	5. #PCDATA = parsed character data sparsowane dane, osnacza ze bedzie tam tekst
	   CDATA= character data znaki które nie są do przeparsowania
	6.(wizytowka*) wystepuje 0 lub więcej razy
	7.(wizytowka+) wystepuje 1 lub więcej razy
	8.(wizytowka?) wystepuje 0 lub 1 raz
	9. znak | :alternatywa oznacza że musie być wybrany chociaż jednen element ale także że mogą byc wybrane oba na raz(+),
	10. <!ATTLIST telefon typ(komorka | stacjonarny) #REQUIED> deklaracja atrybutu, nazwa elelmentu, nazwa atrybutu, zawartość/typ atrybutu, domyślna wartość
	11. rodzaje domyślnej wartośći: #REQUIED, #IMPLIED(opcjonalny)#FIXED(ustalony)
	12. id ID atrybut id o typie ID
-->

=== UKrawczyk-R/kurs_1_html_css_js/cwieczenie-xml+dtd/wizytowki.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE wizytowki SYSTEM "wizytowki.dtd"
[
<!ENTITY strona_www "<website>https://nazwa_strony.pl</website>">
]
>   <!--jeżeli plid dtd jest osobnym plikiem wizytowki.dtd-->
<!-- <!DOCTYPE wizytowki> [ treść dtd] jeżeli mamy mały plik xml to mozemy dtd zrobic w nim ale lepiej miec to zewnętrznie(zrobic wewnętrznie i przenisc do pliku tak najłatwiej) gdyż plik dtd moze byc do wielu xml-->



<wizytowki xmlns:wiz="http://www.w3.org/1999/xhtml">
	<wiz:wizytowka id="a1">
		<imie>Ula</imie>
		<nazwisko>Krawczyk-Rodzim</nazwisko>
		<tel typ="komorka" inny_atrybut="wartosc">tel:12121313</tel>
		<tel typ="stacjonarny">tel:17-23233</tel>
		<e-mail>urszula.karwczyk_007@wp.pl</e-mail>
		&strona_www;
	</wiz:wizytowka>
	
</wizytowki>
